kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST : mysql # mysql component service name


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these lables are deployment lable tiers
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app

  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
        
    spec:
      containers:
      - name: backend
      # check image is exit in docker hb or not
        image: kalyaneswarm/backend:v1.0
        envFrom:
        - ConfigMapRef:
            name: backend

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 # Target port