apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # these lables are deployment lable tiers
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db

  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
        
    spec:
      containers:
      - name: mysql
      # check image is exit in docker hb or not
        image: kalyaneswarm/mysql:v1.0

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 # Target port